// Framer Motion presets — generated by designlang (motionlang)
// Source: https://nordvpn.com/ko/link-checker/
// 2026-06-05T05:14:59.681Z
//
//   import { transitions, variants } from './nordvpn.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0, 0, 0.2, 1], // 185× on page
  custom2: [0.4, 0, 0.2, 1], // 41× on page
  easeIn: [0.4, 0, 1, 1], // 6× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 5× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  sm: 0.25,
  md: 0.3,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.3, ease: easings.easeOut },
  fast:  { duration: 0.150, ease: easings.easeOut },
  slow:  { duration: 0.540, ease: easings.easeOut },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.075 } },
  },
};

export default { easings, durations, transitions, variants };
