// Auto-generated by designlang — component anatomy v2.
// Scaffolds. Wire into your token system; not a runtime library.

import * as React from 'react';

export interface ButtonProps {
  variant?: 'outline' | 'tertiary' | 'primary';
  size?: 'md' | 'medium' | 'sm';
  children?: React.ReactNode;
}

export function Button({ variant = 'outline', size = 'md', ...rest }: ButtonProps) {
  return React.createElement('button', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface CardProps {
  variant?: 'secondary';
  size?: 'md';
  children?: React.ReactNode;
}

export function Card({ variant = 'secondary', size = 'md', ...rest }: CardProps) {
  return React.createElement('div', { 'data-variant': variant, 'data-size': size, ...rest });
}
