// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://nordvpn.com/ko/link-checker/
// Generated: 2026-06-05T05:14:59.679Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#2a2a2d' | '#f7f7f8' | '#4f5054' | '#3e5fff' | '#000000' | '#c8c9cb' | '#696a6d' | '#e2e2e4' | '#b2b2b3' | '#e02f1f' | '#404040' | '#2563eb' | '#141415';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'Noto Sans KR';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700';

export type SpacingToken = '2px' | '16px' | '20px' | '24px' | '32px' | '40px' | '56px' | '64px';

export type RadiusToken = '6px' | '12px' | '20px' | '9999px';

export type DurationToken = '250ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
